FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# music_app

Polls is a simple API allowing consumers to view polls and vote in them.

## Questions Collection [/home_page]

### List All Questions [GET]

+ Response 200 (application/json)

        {
            "status":"success",
            "message":"successfully loaded",
            "data": [
                     {
                      "title":"banner",
                      "items": [
                                {
                                 "name":"banner1",
                                 "image":"https://i.ibb.co/19VZRL4/bg10.jpg"
                                },
                                {
                                 "name":"banner2",
                                 "image":"https://i.ibb.co/j826LL7/esra.jpg"
                                },
                                {
                                 "name":"banner3",
                                 "image":"https://i.ibb.co/61Z053d/download.jpg"
                                }
                            ]
                     },
                     {
                      "title":"trending_songs",
                      "items": [
                                {
                                 "name":"Puthiyoru Pathayil",
                                 "image":"https://i.ibb.co/HGLTFmV/varathan.jpg"
                                },
                                {
                                 "name":"Pyaar Pyaar",
                                 "image":"https://i.ibb.co/NFd3rBK/parava.jpg"
                                },
                                {
                                 "name":"Maranamethunna Nerath",
                                 "image":"https://i.ibb.co/kMD8crK/spirit.jpg"
                                },
                                {
                                 "name":"Thaniye",
                                 "image":"https://i.ibb.co/0ZWzs28/gupi.jpg"
                                }
                            ]
                     },
                     {
                      "title":"top_songs",
                      "items": [
                                {
                                 "name":"Poomuthole",
                                 "image":"https://i.ibb.co/VwCS3H4/joseph.jpg"
                                },
                                {
                                 "name":"Nenjile Nenjile",
                                 "image":"https://i.ibb.co/x2xySNf/1983.jpg"
                                },
                                {
                                 "name":"Njanundivite",
                                 "image":"https://i.ibb.co/860nkxz/pretham.jpg"
                                },
                                {
                                 "name":"Puthyoru Pathayil",
                                 "image":"https://i.ibb.co/HGLTFmV/varathan.jpg"
                                }
                            ]
                     },
                     {
                      "title":"artists",
                      "items": [
                                {
                                 "name":"Yeshudas",
                                 "image":"https://i.ibb.co/mhcwFMx/yeshu-1401893713.jpg"
                                },
                                {
                                 "name":"Sreekumar",
                                 "image":"https://i.ibb.co/S7pmLq6/sreekumar.jpg"
                                },
                                {
                                 "name":"Anu Sithara",
                                 "image":"https://i.ibb.co/kmrbPJp/22687832-1426096807440196-4276502542564884957-n.jpg"
                                },
                                {
                                 "name":"KS Chithra",
                                 "image":"https://i.ibb.co/QQ1XDk6/chithra.jpg"
                                }
                            ]
                     }
                ]
        }
        
        
## Questions Collection [/banner]

### List All Questions [GET]

+ Response 200 (application/json)

        {
            "status":"success",
            "message":"successfully loaded",
            "data": [
                     {
                      "name":"banner1",
                      "image":"https://i.ibb.co/19VZRL4/bg10.jpg"
                      },
                     {
                      "name":"banner2",
                      "image":"https://i.ibb.co/j826LL7/esra.jpg"
                     },
                     {
                       "name":"banner3",
                       "image":"https://i.ibb.co/61Z053d/download.jpg"
                    }
                ]
        }