FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# music_app

Polls is a simple API allowing consumers to view polls and vote in them.

## Questions Collection [/home_page]

### List All Questions [GET]

+ Response 200 (application/json)

        {
            "status":"success",
            "message":"successfully loaded",
            "data": [
                     {
                      "title":"banner",
                      "items": [
                                {
                                 "name":"banner1",
                                 "image":"https://i.ibb.co/19VZRL4/bg10.jpg"
                                },
                                {
                                 "name":"banner2",
                                 "image":"https://i.ibb.co/j826LL7/esra.jpg"
                                },
                                {
                                 "name":"banner3",
                                 "image":"https://i.ibb.co/61Z053d/download.jpg"
                                }
                            ]
                     },
                     {
                      "title":"trending_songs",
                      "items": [
                                {
                                 "name":"Puthiyoru Pathayil",
                                 "image":"https://i.ibb.co/HGLTFmV/varathan.jpg"
                                },
                                {
                                 "name":"Pyaar Pyaar",
                                 "image":"https://i.ibb.co/NFd3rBK/parava.jpg"
                                },
                                {
                                 "name":"Maranamethunna Nerath",
                                 "image":"https://i.ibb.co/kMD8crK/spirit.jpg"
                                }
                            ]
                     },
                ]
        }